application:
  alphabet: "abcdefghijklmnopqrstuvwxyz1234567890"
  timeout: ${TIMEOUT} #ms
  worker-urls: ${WORKER_URLS}
  scheduler-delay: ${SCHEDULER_DELAY} #ms
  max-tasks: ${MAX_IN_PROGRESS_TASKS}
server:
  port: ${SERVER_PORT}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

rabbitmq:
  tasks:
    exchange: ${RABBITMQ_TASKS_EXCHANGE}
    queue: ${RABBITMQ_TASKS_QUEUE}
    key: ${RABBITMQ_TASKS_KEY}
  result:
    exchange: ${RABBITMQ_RESULT_EXCHANGE}
    queue: ${RABBITMQ_RESULT_QUEUE}
    key: ${RABBITMQ_RESULT_KEY}