application:
  alphabet: "abcdefghijklmnopqrstuvwxyz1234567890"
  timeout: ${TIMEOUT} #ms
  worker-urls: ${WORKER_URLS}
  scheduler-delay: ${SCHEDULER_DELAY} #ms
  max-tasks: ${MAX_IN_PROGRESS_TASKS}
server:
  port: ${SERVER_PORT}